bundler_args: --without development production
language: ruby
rvm:
  - 2.1.0
before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-1.2.1.deb && true
  - sudo service elasticsearch start
